pipeline{
    agent any
    
    environment {
        GIT_REPO_URL = 'https://github.com/rakshithr55/devops.git'
        REGISTRY = 'rocky5599/devdocker'
        DOCKERHUB_CREDENTIALS_ID = 'DOCKERHUB_CREDENTIALS_ID' // The ID of the Docker Hub credentials stored in Jenkins
    }
    
    stages{
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Verify Package') {
            steps {
                sh 'ls -l target/'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    echo 'Test Completed!!'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${env.REGISTRY}/build:${env.BUILD_ID}")
                }
                echo 'Image Created!!'
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                    docker.image("${env.REGISTRY}/build:${env.BUILD_ID}").push()
                    }
                }
            }
        }
    }
}
